site_name: FastAPI Paginate
site_author: Nazmul Hasan
site_description: FastAPI Pagination
copyright: "Copyright &copy; 2022 Nazmul Hasan"
repo_url: https://github.com/nazmulnnb/fastapi-paginate
repo_name: nazmulnnb/fastapi-paginate

theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    second: grey
  icon:
    repo: fontawesome/brands/github
  favicon: images/favicon.ico

nav:
  - "Home": index.md
  - "Tutorials":
      - "First Steps": first-steps.md
      - "Operations": filters-sort.md
      - "Customization": customization.md
      - "Advanced": advanced.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - extra
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.inlinehilite

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nazmulnnb/fastapi-paginate